import os
import sys
import re
from playwright.sync_api import sync_playwright

_hermes_home = os.environ.get("HERMES_HOME", os.path.expanduser("~/.hermes"))
_env_path = os.path.join(_hermes_home, ".env")
if os.path.exists(_env_path):
    with open(_env_path, "r", encoding="utf-8") as _f:
        for _line in _f:
            _line = _line.strip()
            if _line and not _line.startswith("#") and "=" in _line:
                _k, _v = _line.split("=", 1)
                os.environ.setdefault(_k.strip(), _v.strip())

USER = os.environ.get("CONGVAN_USER", "")
PASS = os.environ.get("CONGVAN_PASS", "")

if not USER or not PASS:
    print("Vui lòng cấu hình CONGVAN_USER và CONGVAN_PASS trong biến môi trường (.env)", file=sys.stderr)
    sys.exit(1)
BASE = "https://congchuc.quangninh.gov.vn"
LOGIN_URL = BASE + "/SSO/Login.aspx"
DOCS_URL = BASE + "/Default.aspx?tabid=1126"
UNIT = "2256"

print(f"Starting inspection using user: {USER}", file=sys.stderr)

p = sync_playwright().start()
browser = p.chromium.launch(headless=True, args=["--no-sandbox"])
page = browser.new_page()

try:
    # 1. Login
    print("Navigating to login page...", file=sys.stderr)
    page.goto(LOGIN_URL, wait_until="domcontentloaded", timeout=45000)
    page.wait_for_timeout(2000)
    page.evaluate(f"""
        document.getElementById('IDToken1').value = '{USER}';
        document.getElementById('IDToken2').value = '{PASS}';
        document.getElementById('btnLogin').click();
    """)
    page.wait_for_timeout(5000)
    try: page.wait_for_load_state("networkidle", timeout=15000)
    except: pass

    # 2. Select unit
    print(f"Selecting unit {UNIT}...", file=sys.stderr)
    page.goto(BASE + "/Default.aspx?tabid=56", wait_until="domcontentloaded", timeout=30000)
    try: page.wait_for_load_state("networkidle", timeout=15000)
    except: pass
    sel = page.query_selector("select[id$=ddlChonDonVi]")
    if sel:
        sel.select_option(UNIT)
        page.wait_for_timeout(2000)
        try: page.wait_for_load_state("networkidle", timeout=15000)
        except: pass
        print("Unit selected successfully", file=sys.stderr)

    # 3. Navigate to docs grid
    print("Navigating to documents grid...", file=sys.stderr)
    page.goto(DOCS_URL, wait_until="domcontentloaded", timeout=45000)
    page.wait_for_timeout(3000)
    try: page.wait_for_load_state("networkidle", timeout=20000)
    except: pass

    # 4. Find all edit buttons
    print("Finding edit buttons...", file=sys.stderr)
    edit_buttons = page.query_selector_all("[id*='AutoGeneratedEditButton']")
    print(f"Found {len(edit_buttons)} AutoGeneratedEditButton elements:", file=sys.stderr)
    for idx, btn in enumerate(edit_buttons):
        btn_id = btn.get_attribute("id")
        btn_tag = btn.evaluate("el => el.tagName")
        print(f"  [{idx}] Tag: {btn_tag}, ID: {btn_id}", file=sys.stderr)

    if not edit_buttons:
        print("No edit buttons found, taking screenshot and dumping HTML.", file=sys.stderr)
        page.screenshot(path="/opt/data/scripts/congchuc/no_buttons.png")
        with open("/opt/data/scripts/congchuc/no_buttons_page.html", "w", encoding="utf-8") as f:
            f.write(page.content())
        sys.exit(1)

    # Click the first edit button
    target_btn = edit_buttons[0]
    target_id = target_btn.get_attribute("id")
    print(f"Clicking edit button: {target_id}...", file=sys.stderr)
    
    # Save HTML before click
    html_before = page.content()
    
    target_btn.click()
    print("Clicked, waiting for 4 seconds...", file=sys.stderr)
    page.wait_for_timeout(4000)
    try: page.wait_for_load_state("networkidle", timeout=5000)
    except: pass

    # Take screenshot of the dropdown/action state
    screenshot_path = "/opt/data/scripts/congchuc/dropdown.png"
    page.screenshot(path=screenshot_path)
    print(f"Screenshot saved to {screenshot_path}", file=sys.stderr)

    # Save HTML after click
    html_after = page.content()
    with open("/opt/data/scripts/congchuc/dropdown_page.html", "w", encoding="utf-8") as f:
        f.write(html_after)
    print("HTML saved to /opt/data/scripts/congchuc/dropdown_page.html", file=sys.stderr)

    # Analyze HTML after click to find the options
    print("Analyzing page content for action options...", file=sys.stderr)
    keywords = ["Xem", "Trả lại", "Chuyển", "kết thúc", "ket thuc", "Chuyển xử lý"]
    for kw in keywords:
        matches = [m.start() for m in re.finditer(kw, html_after, re.IGNORECASE)]
        print(f"Keyword '{kw}' matches count: {len(matches)}", file=sys.stderr)
        # Find enclosing elements for the first few matches
        for m_idx, start_pos in enumerate(matches[:5]):
            snippet = html_after[max(0, start_pos-100):min(len(html_after), start_pos+150)]
            print(f"  Match [{m_idx}]: ...{snippet}...", file=sys.stderr)

except Exception as e:
    print(f"Error occurred: {e}", file=sys.stderr)
finally:
    browser.close()
    p.stop()
    print("Finished inspection script.", file=sys.stderr)
