import os
import sys
import re
from playwright.sync_api import sync_playwright

_hermes_home = os.environ.get("HERMES_HOME", os.path.expanduser("~/.hermes"))
_env_path = os.path.join(_hermes_home, ".env")
if os.path.exists(_env_path):
    with open(_env_path, "r", encoding="utf-8") as _f:
        for _line in _f:
            _line = _line.strip()
            if _line and not _line.startswith("#") and "=" in _line:
                _k, _v = _line.split("=", 1)
                os.environ.setdefault(_k.strip(), _v.strip())

USER = os.environ.get("CONGVAN_USER", "")
PASS = os.environ.get("CONGVAN_PASS", "")

if not USER or not PASS:
    print("Vui lòng cấu hình CONGVAN_USER và CONGVAN_PASS trong biến môi trường (.env)", file=sys.stderr)
    sys.exit(1)
BASE = "https://congchuc.quangninh.gov.vn"
LOGIN_URL = BASE + "/SSO/Login.aspx"
DOCS_URL = BASE + "/Default.aspx?tabid=1126"
UNIT = "2256"

def setup_page(browser):
    page = browser.new_page()
    page.goto(LOGIN_URL, wait_until="domcontentloaded", timeout=45000)
    page.wait_for_timeout(2000)
    page.evaluate(f"""
        document.getElementById('IDToken1').value = '{USER}';
        document.getElementById('IDToken2').value = '{PASS}';
        document.getElementById('btnLogin').click();
    """)
    page.wait_for_timeout(5000)
    try: page.wait_for_load_state("networkidle", timeout=15000)
    except: pass

    page.goto(BASE + "/Default.aspx?tabid=56", wait_until="domcontentloaded", timeout=30000)
    try: page.wait_for_load_state("networkidle", timeout=15000)
    except: pass
    sel = page.query_selector("select[id$=ddlChonDonVi]")
    if sel:
        sel.select_option(UNIT)
        page.wait_for_timeout(2000)
        try: page.wait_for_load_state("networkidle", timeout=15000)
        except: pass

    page.goto(DOCS_URL, wait_until="domcontentloaded", timeout=45000)
    page.wait_for_timeout(3000)
    try: page.wait_for_load_state("networkidle", timeout=20000)
    except: pass
    return page

p = sync_playwright().start()
browser = p.chromium.launch(headless=True, args=["--no-sandbox"])

# Test 1: Click "Kết thúc"
print("--- TEST 1: KẾT THÚC ---", file=sys.stderr)
try:
    page = setup_page(browser)
    edit_btn = page.query_selector("[id*='AutoGeneratedEditButton']")
    if edit_btn:
        edit_btn.click()
        page.wait_for_timeout(2000)
        
        # Find "Kết thúc" menu item
        ketthuc_link = page.query_selector("text='Kết thúc'")
        if not ketthuc_link:
            # Fallback to finding by class/text
            for a in page.query_selector_all("a.rmLink"):
                if "Kết thúc" in a.inner_text():
                    ketthuc_link = a
                    break
        
        if ketthuc_link:
            print("Found 'Kết thúc' option, clicking...", file=sys.stderr)
            ketthuc_link.click()
            page.wait_for_timeout(4000)
            try: page.wait_for_load_state("networkidle", timeout=5000)
            except: pass
            
            page.screenshot(path="/opt/data/scripts/congchuc/ketthuc_clicked.png")
            with open("/opt/data/scripts/congchuc/ketthuc_page.html", "w", encoding="utf-8") as f:
                f.write(page.content())
            print("Screenshot and HTML saved for 'Kết thúc'", file=sys.stderr)
        else:
            print("Could not find 'Kết thúc' option in menu", file=sys.stderr)
    page.close()
except Exception as e:
    print(f"Error in Test 1: {e}", file=sys.stderr)

# Test 2: Click "Chuyển"
print("--- TEST 2: CHUYỂN ---", file=sys.stderr)
try:
    page = setup_page(browser)
    edit_btn = page.query_selector("[id*='AutoGeneratedEditButton']")
    if edit_btn:
        edit_btn.click()
        page.wait_for_timeout(2000)
        
        chuyen_link = page.query_selector("text='Chuyển'")
        if not chuyen_link:
            for a in page.query_selector_all("a.rmLink"):
                if "Chuyển" in a.inner_text():
                    chuyen_link = a
                    break
        
        if chuyen_link:
            print("Found 'Chuyển' option, clicking...", file=sys.stderr)
            chuyen_link.click()
            page.wait_for_timeout(4000)
            try: page.wait_for_load_state("networkidle", timeout=5000)
            except: pass
            
            page.screenshot(path="/opt/data/scripts/congchuc/chuyen_clicked.png")
            with open("/opt/data/scripts/congchuc/chuyen_page.html", "w", encoding="utf-8") as f:
                f.write(page.content())
            print("Screenshot and HTML saved for 'Chuyển'", file=sys.stderr)
        else:
            print("Could not find 'Chuyển' option in menu", file=sys.stderr)
    page.close()
except Exception as e:
    print(f"Error in Test 2: {e}", file=sys.stderr)

browser.close()
p.stop()
print("Finished action details inspection.", file=sys.stderr)
