import os
import sys
from playwright.sync_api import sync_playwright

_hermes_home = os.environ.get("HERMES_HOME", os.path.expanduser("~/.hermes"))
_env_path = os.path.join(_hermes_home, ".env")
if os.path.exists(_env_path):
    with open(_env_path, "r", encoding="utf-8") as _f:
        for _line in _f:
            _line = _line.strip()
            if _line and not _line.startswith("#") and "=" in _line:
                _k, _v = _line.split("=", 1)
                os.environ.setdefault(_k.strip(), _v.strip())

USER = os.environ.get("CONGVAN_USER", "")
PASS = os.environ.get("CONGVAN_PASS", "")

if not USER or not PASS:
    print("Vui lòng cấu hình CONGVAN_USER và CONGVAN_PASS trong biến môi trường (.env)", file=sys.stderr)
    sys.exit(1)
BASE = "https://congchuc.quangninh.gov.vn"
LOGIN_URL = BASE + "/SSO/Login.aspx"
DOCS_URL = BASE + "/Default.aspx?tabid=1126"
UNIT = "2256"

p = sync_playwright().start()
browser = p.chromium.launch(headless=True, args=["--no-sandbox"])
page = browser.new_page()

try:
    print("Logging in...", file=sys.stderr)
    page.goto(LOGIN_URL, wait_until="domcontentloaded", timeout=45000)
    page.wait_for_timeout(2000)
    page.evaluate(f"""
        document.getElementById('IDToken1').value = '{USER}';
        document.getElementById('IDToken2').value = '{PASS}';
        document.getElementById('btnLogin').click();
    """)
    page.wait_for_timeout(5000)
    try: page.wait_for_load_state("networkidle", timeout=15000)
    except: pass

    print("Selecting unit...", file=sys.stderr)
    page.goto(BASE + "/Default.aspx?tabid=56", wait_until="domcontentloaded", timeout=30000)
    sel = page.query_selector("select[id$=ddlChonDonVi]")
    if sel:
        sel.select_option(UNIT)
        page.wait_for_timeout(2000)
        try: page.wait_for_load_state("networkidle", timeout=15000)
        except: pass

    print("Navigating to grid...", file=sys.stderr)
    page.goto(DOCS_URL, wait_until="domcontentloaded", timeout=45000)
    page.wait_for_timeout(3000)
    try: page.wait_for_load_state("networkidle", timeout=20000)
    except: pass

    # Find first row and its ID
    rows = page.query_selector_all('table.rgMasterTable > tbody > tr.rgRow, table.rgMasterTable > tbody > tr.rgAltRow')
    if not rows:
        print("No documents found in grid", file=sys.stderr)
        sys.exit(1)
    
    first_row = rows[0]
    link = first_row.query_selector('a')
    so_den = link.inner_text().strip() if link else "unknown"
    print(f"First document Số đến: {so_den}", file=sys.stderr)

    edit_btn = first_row.query_selector("[id*='AutoGeneratedEditButton']")
    if not edit_btn:
        print("No edit button on first row", file=sys.stderr)
        sys.exit(1)
        
    print("Clicking edit button...", file=sys.stderr)
    edit_btn.click()
    page.wait_for_timeout(2000)
    
    chuyen_link = page.query_selector("text='Chuyển'")
    if not chuyen_link:
        for a in page.query_selector_all("a.rmLink"):
            if "Chuyển" in a.inner_text():
                chuyen_link = a
                break
                
    if not chuyen_link:
        print("Could not find 'Chuyển' in menu", file=sys.stderr)
        sys.exit(1)
        
    print("Clicking 'Chuyển'...", file=sys.stderr)
    chuyen_link.click()
    page.wait_for_timeout(4000)
    try: page.wait_for_load_state("networkidle", timeout=10000)
    except: pass

    # Wait for the Chuyen screen components
    print("Waiting for 'Chuyển' screen components...", file=sys.stderr)
    page.wait_for_selector('textarea[id$="txtButPheChung"]', timeout=10000)
    
    # Enter test instruction
    print("Entering test instruction in txtButPheChung...", file=sys.stderr)
    page.fill('textarea[id$="txtButPheChung"]', "Ý kiến chuyển tiếp tự động thử nghiệm qua API - Hãy bỏ qua.")

    # Find Khoa Dược or Ban giám đốc in grdPhongBan
    print("Scanning grdPhongBan rows...", file=sys.stderr)
    pb_rows = page.query_selector_all('div[id$="grdPhongBan"] table.rgMasterTable > tbody > tr')
    print(f"Found {len(pb_rows)} rows in grdPhongBan", file=sys.stderr)
    
    target_row = None
    for r in pb_rows:
        text = r.inner_text().strip()
        print(f"  Row text: {text}", file=sys.stderr)
        if "Khoa Dược" in text:
            target_row = r
            print("  -> Found target row (Khoa Dược)!", file=sys.stderr)
            break
            
    if not target_row and len(pb_rows) > 0:
        target_row = pb_rows[0]
        print(f"  -> Target row not found, using first row: {target_row.inner_text().strip()}", file=sys.stderr)

    if target_row:
        # Get checkboxes
        cbs = target_row.query_selector_all('input[type="checkbox"]')
        print(f"Row has {len(cbs)} checkboxes", file=sys.stderr)
        if len(cbs) >= 1:
            print("Checking the first checkbox (Chủ trì)...", file=sys.stderr)
            cbs[0].check()
            page.wait_for_timeout(1000)

    # Take screenshot
    page.screenshot(path="/opt/data/scripts/congchuc/chuyen_selected.png")
    print("Screenshot saved to /opt/data/scripts/congchuc/chuyen_selected.png", file=sys.stderr)

    # Safely close by clicking "Trở về" (btnDong)
    btn_dong = page.query_selector('span[id$="btnDong"]')
    if btn_dong:
        print("Clicking 'Trở về' to close safely...", file=sys.stderr)
        btn_dong.click()
        page.wait_for_timeout(3000)
        try: page.wait_for_load_state("networkidle", timeout=5000)
        except: pass
        print("Closed safely.", file=sys.stderr)
    else:
        print("Could not find 'Trở về' button!", file=sys.stderr)

except Exception as e:
    print(f"Error: {e}", file=sys.stderr)
finally:
    browser.close()
    p.stop()
    print("Finished test_chuyen_select script.", file=sys.stderr)
