#!/usr/bin/env python3
"""Publish MSC watchlist to Zalo deterministically from the same artifact generated by telegram script.

Design:
- Use the exact same source logic/artifact timestamp as Telegram pipeline.
- Generate (or reuse) sidecar + markdown via msc_watchlist_publish_telegram.py with --artifact-ts.
- Send short message to Zalo group from sidecar.short.
"""
from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

WS2 = Path('.')
OUT_DIR = Path(__file__).parent.parent.parent / 'reports/msc_tbmt'
GEN_SCRIPT = WS2 / 'scripts' / 'msc_watchlist_publish_telegram.py'


def _normalize_artifact_ts(raw: str | None) -> str:
    if raw:
        s = raw.strip().replace(' ', '_').replace(':', '-')
        if s:
            return s
    from datetime import datetime
    return datetime.now().strftime('%Y-%m-%d_%H-00')


def _load_sidecar(artifact_ts: str) -> dict:
    p = OUT_DIR / f'msc_tbmt_{artifact_ts}.json'
    if not p.exists():
        raise RuntimeError(f'sidecar_not_found: {p}')
    return json.loads(p.read_text(encoding='utf-8'))


def _ensure_artifact(artifact_ts: str, n: int) -> dict:
    p = subprocess.run(
        ['/opt/homebrew/bin/python3', str(GEN_SCRIPT), '--n', str(n), '--artifact-ts', artifact_ts],
        capture_output=True,
        text=True,
        timeout=300,
    )
    if p.returncode != 0:
        raise RuntimeError(f'generate_artifact_failed: {(p.stderr or p.stdout).strip()}')
    return _load_sidecar(artifact_ts)


def _send_zalo(thread_id: str, message: str) -> str:
    p = subprocess.run(
        ['openclaw', 'message', 'send', '--channel', 'zalouser', '--target', thread_id, '--message', message, '--json'],
        capture_output=True,
        text=True,
        timeout=120,
    )
    raw = ((p.stdout or '') + '\n' + (p.stderr or '')).strip()
    if p.returncode != 0:
        raise RuntimeError(f'zalo_send_failed: {raw}')

    # parse tail json object (CLI may print preamble lines)
    s = raw
    i = s.rfind('{')
    parsed = None
    while i >= 0:
        try:
            obj = json.loads(s[i:])
            parsed = obj.get('payload') if isinstance(obj, dict) and isinstance(obj.get('payload'), dict) else obj
            if isinstance(parsed, dict):
                break
        except Exception:
            pass
        i = s.rfind('{', 0, i)
    if not isinstance(parsed, dict) or not parsed.get('ok'):
        raise RuntimeError(f'zalo_send_not_ok: {raw}')
    return str(parsed.get('messageId') or parsed.get('message_id') or '')


def main() -> int:
    ap = argparse.ArgumentParser(description='Publish deterministic MSC watchlist short report to Zalo.')
    ap.add_argument('--n', type=int, default=999, help='Max units to fetch (default: 999 = all)')
    ap.add_argument('--artifact-ts', required=True, help='Shared artifact timestamp, e.g. 2026-03-23_18-00')
    ap.add_argument('--thread-id', default='2723708131210683420')
    ap.add_argument('--send', action='store_true')
    ns = ap.parse_args()

    art_ts = _normalize_artifact_ts(ns.artifact_ts)
    artifact = _ensure_artifact(art_ts, ns.n)
    filename = artifact.get('filename') or f'msc_tbmt_{art_ts}.md'
    short = str(artifact.get('short') or '').strip()
    if not short:
        raise SystemExit('SENT_FAIL empty_short_message')

    if not ns.send:
        print(json.dumps({'ok': True, 'mode': 'preview', 'artifact_ts': art_ts, 'filename': filename, 'short': short}, ensure_ascii=False, indent=2))
        return 0

    msg_id = _send_zalo(ns.thread_id, short)
    print(f'SENT_OK {filename} zalo={msg_id}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
